### PR TITLE
Remove Hand Raise signal, update design and tidy-up 

### PR DESCRIPTION
**Pull request by kr8n3r**
## Code changes

- **remove Raise hand signal**
Avoid duplication with the built-in Raise hand functionality in Google Meet

- replace individual button components that had very similar but slightly different logic with one `Reaction` component where we pass the type and send the appropriate message and emoji
- cleanup

### Before
Screenshot 2021-07-06 at 18 24 46

### After
Screenshot 2021-07-06 at 18 05 12

Screenshot 2021-07-06 at 18 05 20

## How to test
- remove installed extension
- build and load local - see https://github.com/alphagov/hand-signals#how-to-test-the-extension-locally

### CODE REVIEW

**Review by 0atman — APPROVED** [review]
Nice, I think I see some leftover handup stuff in the dist js and the map - but those will be regenerated I guess?

**Comment by kr8n3r** [comment]
> Nice, I think I see some leftover handup stuff in the dist js and the map - but those will be regenerated I guess?

correct

**Comment by kr8n3r** [comment]
this might constitute a major release ?

**Comment by 0atman** [comment]
I'd vote yes: actual functionality change rather than just UI changes.

**Pull request merged**
